name = "Testmlbbb"
main = "worker.js"
compatibility_date = "2025-08-10"

kv_namespaces = [
  { binding = "PERMANENT_KV", id = "98480fa892684c4f8d601c9f88a99cb0" }
]

[vars]
SECRET_KEY = "3f5a1b2c4d6e7f8091a2b3c4d5e6f708
"
